### ISSUE TITLE
Missing vbproj file

### ISSUE THREAD

**Issue by alenros** [frankk74/innovation#3]
trying to open the solution in Visual Studio 2022, I'm getting an error saying `WinInnovation.vbproj` is missing

**Comment by frankk74** [comment]
Hmmm, I’m not a vs 20xx pro… probably an oppsie on my part… I right clicked and renamed the project inside of vs2022 and was hoping nothing would blow up… could you try copying innovation.vproj to WinInnovation.vproj and restarting vs2022 and see if that fixes it? Or renaming the project back to innovation? Thx!

**Comment by alenros** [comment]
I think the PR wasn't merged.
